

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/layouts/sidebar";
import AppHeader from "@/layouts/header";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex">
          {/* Sidebar fixa */}
          <aside className="fixed top-0 left-0 h-screen w-64 bg-muted/40 border-r border-border z-50">
            <SideBar />
          </aside>

          {/* Área principal */}
          <div className="flex-1 ml-64 flex flex-col min-h-screen transition-all duration-300 ease-in-out">
            {/* Header fixo */}
            <header className="fixed top-0 left-64 right-0 h-16 bg-background border-b z-40 shadow-sm">
              <AppHeader />
            </header>

            {/* Conteúdo da página */}
            <main className="flex-1 pt-16 px-4 md:px-6 bg-[#f7f8f9] dark:bg-inherit overflow-auto">
              <div className="w-full max-w-full">
                {/* <QueryClientProvider client={queryClient}> */}
                  {children}
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>


  );
}
